import type { User, InventoryItem, Order } from './types';

// --- USERS ---
export const users: Omit<User, 'id_usuario'>[] = [
  {
    nombre: 'Santiago Jaquer (Dev)',
    email: 'sjaquer@outlook.es',
    rol: 'Desarrolladores',
    activo: true,
    permisos: {
        puede_crear_pedido: true,
        puede_preparar: true,
        puede_despachar: true,
        puede_confirmar_entrega: true,
        puede_anular: true,
        puede_gestionar_inventario: true,
        puede_ver_reportes: true,
    },
    avatar: 'https://i.pravatar.cc/150?u=sjaquer@outlook.es',
  },
  {
    nombre: 'Ana Valdivia (Admin)',
    email: 'admin@example.com',
    rol: 'Admin',
    activo: true,
    permisos: {
        puede_crear_pedido: true,
        puede_preparar: true,
        puede_despachar: true,
        puede_confirmar_entrega: true,
        puede_anular: true,
        puede_gestionar_inventario: true,
        puede_ver_reportes: true,
    },
     avatar: 'https://i.pravatar.cc/150?u=admin@example.com',
  },
  {
    nombre: 'Carlos Solis (Call Center)',
    email: 'callcenter@example.com',
    rol: 'Call Center',
    activo: true,
    permisos: {
        puede_crear_pedido: true,
        puede_preparar: false,
        puede_despachar: false,
        puede_confirmar_entrega: false,
        puede_anular: false,
        puede_gestionar_inventario: false,
        puede_ver_reportes: false,
    },
     avatar: 'https://i.pravatar.cc/150?u=callcenter@example.com',
  },
   {
    nombre: 'Lucia Ferreyra (Logística)',
    email: 'logistica@example.com',
    rol: 'Logistica',
    activo: true,
    permisos: {
        puede_crear_pedido: false,
        puede_preparar: true,
        puede_despachar: true,
        puede_confirmar_entrega: true,
        puede_anular: true,
        puede_gestionar_inventario: true,
        puede_ver_reportes: true,
    },
     avatar: 'https://i.pravatar.cc/150?u=logistica@example.com',
  },
  {
    nombre: 'Jorge Campos (Empacado)',
    email: 'empacado@example.com',
    rol: 'Empacado',
    activo: true,
    permisos: {
        puede_crear_pedido: false,
        puede_preparar: true,
        puede_despachar: false,
        puede_confirmar_entrega: false,
        puede_anular: false,
        puede_gestionar_inventario: false,
        puede_ver_reportes: false,
    },
     avatar: 'https://i.pravatar.cc/150?u=empacado@example.com',
  },
  {
    nombre: 'Maria Delgado (Marketing)',
    email: 'marketing@example.com',
    rol: 'Marketing',
    activo: true,
    permisos: {
        puede_crear_pedido: true,
        puede_preparar: false,
        puede_despachar: false,
        puede_confirmar_entrega: false,
        puede_anular: false,
        puede_gestionar_inventario: false,
        puede_ver_reportes: true,
    },
     avatar: 'https://i.pravatar.cc/150?u=marketing@example.com',
  },
  {
    nombre: 'Miguel Castro (Jefatura)',
    email: 'jefatura@example.com',
    rol: 'Jefatura',
    activo: true,
    permisos: {
        puede_crear_pedido: true,
        puede_preparar: true,
        puede_despachar: true,
        puede_confirmar_entrega: true,
        puede_anular: true,
        puede_gestionar_inventario: true,
        puede_ver_reportes: true,
    },
     avatar: 'https://i.pravatar.cc/150?u=jefatura@example.com',
  },
];


// --- INVENTORY ---
export const inventory: Omit<InventoryItem, 'sku'>[] = [
    {
        id_producto_base: 'PROD-001',
        nombre: 'Zapatillas Deportivas Runner Pro',
        tienda: 'Trazto',
        descripcion: 'Zapatillas ligeras para corredores de alto rendimiento.',
        stock_actual: 50,
        stock_minimo: 10,
        ubicacion_almacen: 'A-1-1',
        precios: { compra: 80, venta: 150 },
        proveedor: { id_proveedor: 'PV-01', nombre: 'Sportify S.A.' },
        estado: 'ACTIVO',
        variantes: [],
        historial_stock: [],
    },
    {
        id_producto_base: 'PROD-002',
        nombre: 'Mochila Urbana Impermeable',
        tienda: 'Trazto',
        descripcion: 'Mochila resistente al agua, ideal para la ciudad.',
        stock_actual: 8,
        stock_minimo: 5,
        ubicacion_almacen: 'B-2-3',
        precios: { compra: 50, venta: 95 },
        proveedor: { id_proveedor: 'PV-02', nombre: 'UrbanGear Co.' },
        estado: 'ACTIVO',
        variantes: [],
        historial_stock: [],
    },
    {
        id_producto_base: 'PROD-003',
        nombre: 'Audífonos Bluetooth ProSound',
        tienda: 'Blumi',
        descripcion: 'Sonido de alta fidelidad con cancelación de ruido.',
        stock_actual: 0,
        stock_minimo: 10,
        ubicacion_almacen: 'C-4-1',
        precios: { compra: 120, venta: 250 },
        proveedor: { id_proveedor: 'PV-03', nombre: 'TechElec' },
        estado: 'SIN_STOCK',
        variantes: [],
        historial_stock: [],
    },
    {
        id_producto_base: 'PROD-004',
        nombre: 'Lentes de Sol Aviador Clásico',
        tienda: 'Dearel',
        descripcion: 'Protección UV400, estilo atemporal.',
        stock_actual: 40,
        stock_minimo: 15,
        ubicacion_almacen: 'A-3-5',
        precios: { compra: 30, venta: 75 },
        proveedor: { id_proveedor: 'PV-01', nombre: 'Sportify S.A.' },
        estado: 'ACTIVO',
        variantes: [],
        historial_stock: [],
    },
    {
        id_producto_base: 'PROD-005',
        nombre: 'Smartwatch FitLife 2',
        tienda: 'Blumi',
        descripcion: 'Monitor de actividad, ritmo cardíaco y notificaciones.',
        stock_actual: 25,
        stock_minimo: 5,
        ubicacion_almacen: 'C-1-2',
        precios: { compra: 200, venta: 380 },
        proveedor: { id_proveedor: 'PV-03', nombre: 'TechElec' },
        estado: 'ACTIVO',
        variantes: [],
        historial_stock: [],
    },
     {
        id_producto_base: 'PROD-006',
        nombre: 'Casaca Cortavientos',
        tienda: 'Cumbre',
        descripcion: 'Casaca ultra ligera para protección contra el viento y la llovizna.',
        stock_actual: 15,
        stock_minimo: 5,
        ubicacion_almacen: 'B-1-1',
        precios: { compra: 60, venta: 130 },
        proveedor: { id_proveedor: 'PV-02', nombre: 'UrbanGear Co.' },
        estado: 'ACTIVO',
        variantes: [],
        historial_stock: [],
    },
    {
        id_producto_base: 'PROD-007',
        nombre: 'Taza de Cerámica "Code Mode"',
        tienda: 'Trazto',
        descripcion: 'Taza de 15oz para tu bebida favorita mientras programas.',
        stock_actual: 100,
        stock_minimo: 20,
        ubicacion_almacen: 'D-1-1',
        precios: { compra: 15, venta: 35 },
        proveedor: { id_proveedor: 'PV-04', nombre: 'Regalos Creativos' },
        estado: 'ACTIVO',
        variantes: [],
        historial_stock: [],
    },
];

// --- ORDERS ---
export const orders: Omit<Order, 'id_pedido' | 'id_interno' | 'asignacion' | 'items' | 'historial'>[] = [
    {
        tienda: { id_tienda: 'T01', nombre: 'Trazto' },
        estado_actual: 'PENDIENTE',
        cliente: { id_cliente: 'C001', nombres: 'Juan Pérez', dni: '45678912', celular: '987654321' },
        pago: { monto_total: 185.00, monto_pendiente: 185.00, metodo_pago_previsto: 'YAPE', estado_pago: 'PENDIENTE', comprobante_url: null, fecha_pago: null },
        envio: { tipo: 'LIMA', provincia: 'Lima', direccion: 'Av. La Marina 123, San Miguel', courier: 'INTERNO', agencia_shalom: null, nro_guia: null, link_seguimiento: null, costo_envio: 10.00 },
        fechas_clave: { creacion: '2023-10-26T10:00:00Z', preparacion: null, despacho: null, entrega_estimada: '2023-10-28T18:00:00Z', entrega_real: null, anulacion: null },
        notas: { nota_pedido: 'Entregar en portería.', observaciones_internas: '', motivo_anulacion: null },
    },
    {
        tienda: { id_tienda: 'T02', nombre: 'Cumbre' },
        estado_actual: 'ENTREGADO',
        cliente: { id_cliente: 'C002', nombres: 'María López', dni: '12345678', celular: '912345678' },
        pago: { monto_total: 95.00, monto_pendiente: 0.00, metodo_pago_previsto: 'Efectivo', estado_pago: 'PAGADO', comprobante_url: null, fecha_pago: '2023-10-25T15:30:00Z' },
        envio: { tipo: 'LIMA', provincia: 'Lima', direccion: 'Recojo en tienda', courier: 'INTERNO', agencia_shalom: null, nro_guia: null, link_seguimiento: null, costo_envio: 0.00 },
        fechas_clave: { creacion: '2023-10-25T15:25:00Z', preparacion: '2023-10-25T15:28:00Z', despacho: '2023-10-25T15:30:00Z', entrega_estimada: '2023-10-25T15:30:00Z', entrega_real: '2023-10-25T15:30:00Z', anulacion: null },
        notas: { nota_pedido: '', observaciones_internas: 'Cliente solicitó bolsa de regalo.', motivo_anulacion: null },
    },
    {
        tienda: { id_tienda: 'T01', nombre: 'Trazto' },
        estado_actual: 'EN_TRANSITO_PROVINCIA',
        cliente: { id_cliente: 'C003', nombres: 'Carlos Sanchez', dni: '87654321', celular: '998877665' },
        pago: { monto_total: 405.00, monto_pendiente: 0.00, metodo_pago_previsto: 'Tarjeta de Crédito', estado_pago: 'PAGADO', comprobante_url: 'https://comprobante.com/pago3.jpg', fecha_pago: '2023-10-24T09:00:00Z' },
        envio: { tipo: 'PROVINCIA', provincia: 'Arequipa', direccion: 'Urb. Yanahuara K-10', courier: 'SHALOM', agencia_shalom: 'Agencia Arequipa Centro', nro_guia: 'SH-55-2023-9876', link_seguimiento: 'https://shalom.com.pe/seguimiento/SH-55-2023-9876', costo_envio: 25.00 },
        fechas_clave: { creacion: '2023-10-24T09:00:00Z', preparacion: '2023-10-24T14:00:00Z', despacho: '2023-10-24T18:00:00Z', entrega_estimada: '2023-10-27T18:00:00Z', entrega_real: null, anulacion: null },
        notas: { nota_pedido: 'Por favor, embalar con cuidado, son productos frágiles.', observaciones_internas: '', motivo_anulacion: null },
    },
    {
        tienda: { id_tienda: 'T03', nombre: 'Dearel' },
        estado_actual: 'ANULADO',
        cliente: { id_cliente: 'C004', nombres: 'Laura Fernandez', dni: '11223344', celular: '911223344' },
        pago: { monto_total: 75.00, monto_pendiente: 75.00, metodo_pago_previsto: 'Transferencia Bancaria', estado_pago: 'PENDIENTE', comprobante_url: null, fecha_pago: null },
        envio: { tipo: 'LIMA', provincia: 'Lima', direccion: 'Calle Los Pinos 456, Surco', courier: 'OLVA', agencia_shalom: null, nro_guia: null, link_seguimiento: null, costo_envio: 12.00 },
        fechas_clave: { creacion: '2023-10-23T11:00:00Z', preparacion: null, despacho: null, entrega_estimada: '2023-10-25T18:00:00Z', entrega_real: null, anulacion: '2023-10-23T16:00:00Z' },
        notas: { nota_pedido: '', observaciones_internas: 'Cliente se desistió de la compra.', motivo_anulacion: 'Cliente se desistió' },
    },
    {
        tienda: { id_tienda: 'T01', nombre: 'Trazto' },
        estado_actual: 'EN_PREPARACION',
        cliente: { id_cliente: 'C005', nombres: 'Pedro Gomez', dni: '44556677', celular: '944556677' },
        pago: { monto_total: 130.00, monto_pendiente: 0.00, metodo_pago_previsto: 'PLIN', estado_pago: 'PAGADO', comprobante_url: 'https://comprobante.com/pago5.jpg', fecha_pago: '2023-10-26T12:00:00Z' },
        envio: { tipo: 'LIMA', provincia: 'Lima', direccion: 'Jirón de la Unión 899, Cercado', courier: 'INTERNO', agencia_shalom: null, nro_guia: null, link_seguimiento: null, costo_envio: 10.00 },
        fechas_clave: { creacion: '2023-10-26T12:00:00Z', preparacion: '2023-10-26T14:00:00Z', despacho: null, entrega_estimada: '2023-10-27T18:00:00Z', entrega_real: null, anulacion: null },
        notas: { nota_pedido: 'Tocar el intercomunicador 301.', observaciones_internas: 'Verificar stock de Casaca.', motivo_anulacion: null },
    }
];
