// This file now contains the legacy data structures, which are used to seed the database.
// The application will fetch data from Firestore directly.

import type { LegacyOrder, LegacyUser, LegacyInventoryItem } from './types';

export const users: LegacyUser[] = [
  { id: 'user-1', name: 'Ana Garcia', email: 'ana.garcia@example.com', avatar: '/avatars/01.png', role: 'OPERADOR_LOGISTICO' },
  { id: 'user-2', name: 'Carlos Rodriguez', email: 'carlos.rodriguez@example.com', avatar: '/avatars/02.png', role: 'OPERADOR_LOGISTICO' },
  { id: 'user-3', name: 'Sofia Martinez', email: 'sofia.martinez@example.com', avatar: '/avatars/03.png', role: 'ADMINISTRADOR' },
  { id: 'user-4', name: 'Luis Hernandez', email: 'luis.h@example.com', avatar: '/avatars/04.png', role: 'GERENTE' },
];

export const inventory: LegacyInventoryItem[] = [
  { id: 'item-1', sku: 'LAP-001', name: 'Laptop Pro 15"', description: 'Laptop potente para profesionales', stock: 25, lowStockThreshold: 10, location: 'Almacén A-1', price: 1200, supplier: 'TechSupplier Inc.', isDiscontinued: false },
  { id: 'item-2', sku: 'MON-002', name: 'Monitor 4K 27"', description: 'Monitor Ultra HD para visuales nítidos', stock: 8, lowStockThreshold: 5, location: 'Almacén B-2', price: 450, supplier: 'Vision Electronics', isDiscontinued: false },
  { id: 'item-3', sku: 'KBD-003', name: 'Teclado Mecánico', description: 'Teclado mecánico gamer RGB', stock: 50, lowStockThreshold: 15, location: 'Almacén A-1', price: 150, supplier: 'Gadget World', isDiscontinued: false },
  { id: 'item-4', sku: 'MSE-004', name: 'Mouse Inalámbrico', description: 'Mouse inalámbrico ergonómico', stock: 3, lowStockThreshold: 5, location: 'Almacén C-3', price: 80, supplier: 'Gadget World', isDiscontinued: false },
  { id: 'item-5', sku: 'CAM-005', name: 'Webcam HD 1080p', description: 'Webcam de alta definición para streaming', stock: 0, lowStockThreshold: 5, location: 'Almacén B-2', price: 95, supplier: 'Vision Electronics', isDiscontinued: false },
  { id: 'item-6', sku: 'DOCK-006', name: 'Estación de Acoplamiento USB-C', description: 'Conecta todos tus periféricos', stock: 12, lowStockThreshold: 5, location: 'Almacén A-1', price: 250, supplier: 'TechSupplier Inc.', isDiscontinued: true },
];

export const orders: LegacyOrder[] = [
  {
    id: '#38201',
    client: { name: 'Lucia Fernandez', address: 'Av. Siempre Viva 123, Lima' },
    shop: 'Tienda Online',
    items: [{ itemId: 'item-1', quantity: 1, estado_item: 'PENDIENTE' }, { itemId: 'item-4', quantity: 1, estado_item: 'PENDIENTE' }],
    totalAmount: 1280,
    paymentMethod: 'Tarjeta de Crédito',
    estado_pago: 'PAGADO',
    assignedUserId: 'user-1',
    courier: 'URBANO',
    fecha_creacion: '2024-05-20T10:00:00Z',
    fecha_estimada_entrega: '2024-05-23T18:00:00Z',
    estado_actual: 'PENDIENTE',
  },
  {
    id: '#38202',
    client: { name: 'Javier Torres', address: 'Calle Falsa 456, Arequipa' },
    shop: 'Tienda Física',
    items: [{ itemId: 'item-2', quantity: 2, estado_item: 'PENDIENTE' }],
    totalAmount: 900,
    paymentMethod: 'Efectivo',
    estado_pago: 'PAGADO',
    assignedUserId: 'user-2',
    courier: 'SHALOM',
    fecha_creacion: '2024-05-21T11:30:00Z',
    fecha_estimada_entrega: '2024-05-26T18:00:00Z',
    estado_actual: 'EN_PREPARACION',
    fecha_preparacion: '2024-05-21T14:00:00Z',
  },
  {
    id: '#38203',
    client: { name: 'Maria Lopez', address: 'Jr. de la Unión 789, Lima' },
    shop: 'Marketplace',
    items: [{ itemId: 'item-3', quantity: 1, estado_item: 'PENDIENTE' }],
    totalAmount: 150,
    paymentMethod: 'Transferencia Bancaria',
    estado_pago: 'PENDIENTE',
    assignedUserId: 'user-1',
    courier: 'INTERNO',
    fecha_creacion: '2024-05-21T15:00:00Z',
    fecha_estimada_entrega: '2024-05-22T18:00:00Z',
    estado_actual: 'EN_TRANSITO_LIMA',
    fecha_preparacion: '2024-05-21T16:00:00Z',
    fecha_transito: '2024-05-21T18:00:00Z',
    trackingNumber: 'INT-54321',
  },
  {
    id: '#38204',
    client: { name: 'Pedro Ramirez', address: 'Av. El Sol 321, Cusco' },
    shop: 'Tienda Online',
    items: [{ itemId: 'item-1', quantity: 1, estado_item: 'PENDIENTE' }, { itemId: 'item-5', quantity: 1, estado_item: 'PENDIENTE' }],
    totalAmount: 1295,
    paymentMethod: 'Tarjeta de Crédito',
    estado_pago: 'PAGADO',
    assignedUserId: 'user-2',
    courier: 'OLVA',
    fecha_creacion: '2024-05-18T09:00:00Z',
    fecha_estimada_entrega: '2024-05-25T18:00:00Z',
    estado_actual: 'EN_TRANSITO_PROVINCIA',
    fecha_preparacion: '2024-05-18T12:00:00Z',
    fecha_transito: '2024-05-19T10:00:00Z',
    trackingNumber: 'OLVA-98765',
  },
  {
    id: '#38205',
    client: { name: 'Elena Quispe', address: 'Av. Larco 101, Lima' },
    shop: 'Tienda Física',
    items: [{ itemId: 'item-4', quantity: 1, estado_item: 'PENDIENTE' }],
    totalAmount: 80,
    paymentMethod: 'Efectivo',
    estado_pago: 'PAGADO',
    assignedUserId: 'user-1',
    courier: 'URBANO',
    fecha_creacion: '2024-05-15T13:00:00Z',
    fecha_estimada_entrega: '2024-05-16T18:00:00Z',
    fecha_entrega_real: '2024-05-16T15:30:00Z',
    estado_actual: 'ENTREGADO',
    fecha_preparacion: '2024-05-15T14:00:00Z',
    fecha_transito: '2024-05-16T10:00:00Z',
    trackingNumber: 'URB-12345',
  },
   {
    id: '#38206',
    client: { name: 'Isabel Castillo', address: 'Calle Grau 555, Piura' },
    shop: 'Tienda Online',
    items: [{ itemId: 'item-6', quantity: 1, estado_item: 'PENDIENTE' }],
    totalAmount: 250,
    paymentMethod: 'Tarjeta de Crédito',
    estado_pago: 'PAGADO',
    assignedUserId: 'user-2',
    courier: 'SHALOM',
    fecha_creacion: '2024-05-22T08:00:00Z',
    fecha_estimada_entrega: '2024-05-28T18:00:00Z',
    estado_actual: 'RETENIDO',
  },
  {
    id: '#38207',
    client: { name: 'Ricardo Vargas', address: 'Av. Arequipa 2020, Lima' },
    shop: 'Marketplace',
    items: [{ itemId: 'item-2', quantity: 1, estado_item: 'PENDIENTE' }, { itemId: 'item-3', quantity: 1, estado_item: 'PENDIENTE' }],
    totalAmount: 600,
    paymentMethod: 'Transferencia Bancaria',
    estado_pago: 'PAGADO',
    assignedUserId: 'user-1',
    courier: 'URBANO',
    fecha_creacion: '2024-05-20T16:00:00Z',
    fecha_estimada_entrega: '2024-05-21T18:00:00Z',
    estado_actual: 'ANULADO',
  },
  {
    id: '#38208',
    client: { name: 'Daniel Mendoza', address: 'Av. Pardo 555, Miraflores' },
    shop: 'Tienda Online',
    items: [{ itemId: 'item-1', quantity: 2, estado_item: 'PENDIENTE' }],
    totalAmount: 2400,
    paymentMethod: 'Tarjeta de Crédito',
    estado_pago: 'PAGADO',
    assignedUserId: 'user-1',
    courier: 'INTERNO',
    fecha_creacion: '2024-05-23T14:00:00Z',
    fecha_estimada_entrega: '2024-05-24T18:00:00Z',
    estado_actual: 'PENDIENTE',
  },
  {
    id: '#38209',
    client: { name: 'Valeria Reyes', address: 'Calle Berlin 123, Miraflores' },
    shop: 'Tienda Física',
    items: [{ itemId: 'item-3', quantity: 5, estado_item: 'PENDIENTE' }],
    totalAmount: 750,
    paymentMethod: 'Efectivo',
    estado_pago: 'PAGADO',
    assignedUserId: 'user-2',
    courier: 'INTERNO',
    fecha_creacion: '2024-05-24T10:00:00Z',
    fecha_estimada_entrega: '2024-05-24T12:00:00Z',
    estado_actual: 'PENDIENTE',
  },
   {
    id: '#38210',
    client: { name: 'Juan Perez', address: 'Av. Brasil 1500, Lima' },
    shop: 'Tienda Online',
    items: [{ itemId: 'item-2', quantity: 1, estado_item: 'PENDIENTE' }],
    totalAmount: 450,
    paymentMethod: 'Tarjeta de Crédito',
    estado_pago: 'PAGADO',
    assignedUserId: 'user-1',
    courier: 'URBANO',
    fecha_creacion: '2024-05-18T10:00:00Z',
    fecha_estimada_entrega: '2024-05-20T18:00:00Z',
    fecha_entrega_real: '2024-05-21T11:00:00Z', // Delayed
    estado_actual: 'ENTREGADO',
    fecha_preparacion: '2024-05-18T14:00:00Z',
    fecha_transito: '2024-05-19T10:00:00Z',
  },
];
